# Лабораторная работа №1. Методы сортировки
## Выполнил студент группы БВТ2003 Гореликов Владислав
### Задание №1
Описание условия задания:
1. Создать Jupyter Notebook со следующим наименованием: Lab1_Группа_ФИО
2. Создать новую ячейку с помощью кнопки
3. В созданной ячейке по указанной ниже форме заполните оглавление файла, заменив наименование группы и вписав све ФИО, после чего создайте еще одну ячейку и напишите следующий код:
4. С помощью кнопки запустите выполнение всех ячеек
5. После выполнения у вас должна отформатироваться ячейка с оглавлением и должен выполниться “Hello, World!”

In [3]:
print("Hello, World!")

Hello, World!


## Задание №2
Описание условия задания:  
Написать генератор случайных матриц(многомерных), который принимает опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер матрицы, а min_lim и max_lim - минимальное и максимальное значение для генерируемого числа. По умолчанию при отсутствии параметров принимать следующие значения:  
m = 50
n = 50
min_limit = -250
max_limit = 1005

In [32]:
import random
import numpy

#Создание матрицы
m = 50
n = 50
min_limit = -250
max_limit = 1005
strM = input("m = ")
if len(strM) > 0: m = int(strM)
strN = input("Введите n = ")
if len(strN) > 0: n = int(strN)
while True:
    strMin_limit = input("min_limit = ")
    if len(strMin_limit) > 0: min_limit = int(strMin_limit)
    strMax_limit = input("max_limit = ")
    if len(strMax_limit) > 0: max_limit = int(strMax_limit)
    if min_limit <= max_limit:
        break
    else:
        print("\nМинимальный элемент не может быть больше максимального!\n")

matrix = numpy.zeros((m, n))

for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(int(min_limit), int(max_limit))
print("Матрица: ")
print(matrix)

m = 10
Введите n = 10
min_limit = 1
max_limit = 9
Матрица: 
[[8. 5. 3. 3. 8. 6. 1. 8. 4. 4.]
 [1. 6. 2. 4. 3. 3. 9. 9. 9. 1.]
 [2. 2. 9. 5. 2. 9. 2. 3. 8. 5.]
 [4. 6. 2. 3. 6. 9. 7. 2. 8. 2.]
 [2. 8. 2. 8. 1. 9. 9. 3. 4. 7.]
 [3. 8. 5. 9. 7. 9. 6. 4. 5. 8.]
 [5. 6. 2. 2. 6. 5. 4. 5. 1. 8.]
 [6. 9. 3. 7. 4. 7. 1. 6. 3. 7.]
 [6. 3. 4. 7. 6. 8. 9. 4. 7. 3.]
 [7. 6. 1. 1. 5. 7. 5. 4. 7. 9.]]


## Задание №3
Описание условия задания:  
Реализовать методы сортировки строк числовой матрицы в соответствии с заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со временем стандартной функции сортировки. Испытания проводить на сгенерированных матрицах  
Методы:  
| Выбором | Вставкой | Обменом | Шелла | Турнирная | Быстрая сортировка | Пирамидальная | 

In [3]:
import timeit
import random
import numpy

# Сортировка выбором: берем самый первый элемент, сравниваем с 1, 2 и тд, и меняем местами, так до конца O(n^2)
def SelectionSort(matrix):
    sel_array = matrix
    for i in range(m):
        for j in range(n - 1):
            min = j
            for h in range(j + 1, n):
                if sel_array[i][h] < sel_array[i][min]:
                    min = h
            temp = sel_array[i][j]
            sel_array[i][j] = sel_array[i][min]
            sel_array[i][min] = temp
    return sel_array


# Сортировка вставкой: последний элемент сравниваем со всеми, меняем местами с большим, и так до конца O(n^2)
def InsertionSort(matrix):
    ins_array = matrix.copy()
    for i in range(len(ins_array)):
        for j in range(len(ins_array[i])):
            temp = ins_array[i][j]
            index = j
            while (temp < ins_array[i][index - 1]) and (index > 0):
                ins_array[i][index] = ins_array[i][index - 1]
                index -= 1
            ins_array[i][index] = temp
    return ins_array


# Сортировка обменом: сравниваем попарно элементы, и так несколько раз по кругу O(n)-лучш, n2
def BubbleSort(matrix):
    bub_array = matrix.copy()
    for i in range(len(bub_array)):
        for j in range(len(bub_array[i])):
            for h in range(len(bub_array[i]) - j - 1):
                if bub_array[i][h + 1] < bub_array[i][h]:
                    temp = bub_array[i][h]
                    bub_array[i][h] = bub_array[i][h + 1]
                    bub_array[i][h + 1] = temp
    return bub_array


# Сортировка Шелла: улучшенная сортировка вставкой, сравнение 1 числа с серединой, и т.д. со сдвигом 1. Затем уменьшаем вдвое интервал
#b:n, 
def ShellSort(matrix):
    shell_array = matrix.copy()
    for i in range(len(shell_array)):
        d = int(len(shell_array[i]) / 2)
        while d > 0:
            for j in range(len(shell_array[i])):
                for h in range(int(j + d), len(shell_array[i]), d):
                    if shell_array[i][j] > shell_array[i][h]:
                        temp = shell_array[i][j]
                        shell_array[i][j] = shell_array[i][h]
                        shell_array[i][h] = temp

            d = int(d / 2)
    return shell_array


# Сортировка Турнирная nlog2n
def TournamentSort(matrix):
    tour_array = matrix.copy()
    for i in range(len(tour_array)):
        tournamentSort(tour_array[i])
    return tour_array


def tournamentSort(tour_array):
    tree = [None] * 2 * (len(tour_array) + len(tour_array) % 2)
    index = len(tree) - len(tour_array) - len(tour_array) % 2

    for i, v in enumerate(tour_array):
        tree[index + i] = (i, v)

    for j in range(len(tour_array)):
        n = len(tour_array)
        index = len(tree) - len(tour_array) - len(tour_array) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1)
                if tree[i] is not None and tree[i + 1] is not None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] is not None else tree[i + 1]
            index -= n

        index, x = tree[0]
        tour_array[j] = x
        tree[len(tree) - len(tour_array) - len(tour_array) % 2 + index] = None

 
    
# Сортировка Быстрая n logn
def QuickSort(matrix):
    qui_array = matrix.copy()
    for i in range(len(qui_array)):
        quickSort(0, len(qui_array[i]) - 1, qui_array, i)
    return qui_array


def quickSort(_first, _last, matrix, row):
    first = int(_first)
    last = int(_last)
    middle = int((first + last) / 2)

    while first < last:

        while matrix[row][first] < matrix[row][middle]:
            first += 1
        while matrix[row][last] > matrix[row][middle]:
            last -= 1
        if first <= last:
            matrix[row][first], matrix[row][last] = matrix[row][last], matrix[row][first]
            first += 1
            last -= 1

    if _first < last:
        quickSort(_first, last, matrix, row)
    if first < _last:
        quickSort(first, _last, matrix, row)


# Сортировка Пирамидальная n logn
def heapify(heap_array, n, i):
    largest = i
    l = 2 * i + 1
    r = 2 * i + 2

    if l < n and heap_array[i] < heap_array[l]:
        largest = l
    if r < n and heap_array[largest] < heap_array[r]:
        largest = r
    if largest != i:
        heap_array[i], heap_array[largest] = heap_array[largest], heap_array[i]
        heapify(heap_array, n, largest)

def HeapSort(matrix):
    heap_array = matrix.copy()
    for i in range(len(heap_array)):
        n = len(heap_array[i])
        
        for j in range(n, -1, -1):
            heapify(heap_array[i], n, j)
            
        for j in range(n - 1, 0, -1):
            heap_array[i][j], heap_array[i][0] = heap_array[i][0], heap_array[i][j]
            heapify(heap_array[i], j, 0)
    return heap_array


#Создание матрицы
m = 50
n = 50
min_limit = -250
max_limit = 1005
strM = input("m = ")
if len(strM) > 0: m = int(strM)
strN = input("Введите n = ")
if len(strN) > 0: n = int(strN)
while True:
    strMin_limit = input("min_limit = ")
    if len(strMin_limit) > 0: min_limit = int(strMin_limit)
    strMax_limit = input("max_limit = ")
    if len(strMax_limit) > 0: max_limit = int(strMax_limit)
    if min_limit <= max_limit:
        break
    else:
        print("\nМинимальный элемент не может быть больше максимального!\n")

matrix = numpy.zeros((m, n))

for i in range(m):
    for j in range(n):
        matrix[i][j] = random.randint(int(min_limit), int(max_limit))
print("Матрица: ")
print(matrix)
print("\n")

#Вывод
print("Cортировка выбором: ")
start_time = timeit.default_timer()
SelectionSort(matrix)
time_fin = timeit.default_timer() - start_time
print(time_fin)
print("\n")

print("Сортировка вставкой: ")
start_time = timeit.default_timer()
InsertionSort(matrix)
time_fin = timeit.default_timer() - start_time
print(time_fin)
print("\n")

print("Сортировка обменом: ")
start_time = timeit.default_timer()
BubbleSort(matrix)
time_fin = timeit.default_timer() - start_time
print(time_fin)
print("\n")

print("Сортировка Шелла: ")
start_time = timeit.default_timer()
ShellSort(matrix)
time_fin = timeit.default_timer() - start_time
print(time_fin)
print("\n")

print("Турнирная сортировка: ")
start_time = timeit.default_timer()
TournamentSort(matrix)
time_fin = timeit.default_timer() - start_time
print(time_fin)
print("\n")

print("Быстрая сортировка: ")
start_time = timeit.default_timer()
QuickSort(matrix)
time_fin = timeit.default_timer() - start_time
print(time_fin)
print("\n")

print("Пирамидальная сортировка: ")
start_time = timeit.default_timer()
HeapSort(matrix)
time_fin = timeit.default_timer() - start_time
print(time_fin)

m = 10
Введите n = 10
min_limit = 1
max_limit = 9
Матрица: 
[[1. 5. 3. 5. 6. 7. 6. 3. 2. 9.]
 [1. 4. 3. 7. 3. 9. 9. 7. 1. 3.]
 [8. 9. 5. 6. 7. 6. 1. 2. 7. 1.]
 [3. 9. 9. 8. 5. 4. 8. 5. 8. 8.]
 [1. 1. 6. 6. 8. 7. 3. 4. 3. 3.]
 [1. 9. 4. 4. 3. 8. 6. 3. 1. 6.]
 [5. 4. 7. 3. 5. 4. 5. 1. 7. 9.]
 [4. 8. 8. 4. 3. 5. 9. 6. 7. 6.]
 [4. 9. 4. 1. 2. 4. 4. 9. 1. 7.]
 [8. 2. 1. 6. 6. 1. 6. 5. 5. 9.]]


Cортировка выбором: 
0.0007673000000067987


Сортировка вставкой: 
0.00029829999999719803


Сортировка обменом: 
0.0006494999999517859


Сортировка Шелла: 
0.0011382999999796084


Турнирная сортировка: 
0.0016219999999975698


Быстрая сортировка: 
0.0006983999999761181


Пирамидальная сортировка: 
0.0008952000000022053


## Задание №4
Создать публичный репозиторий на github, и запушить выполненное задание в
.ipynb формате.

## Вывод: 
В данной лараторной работе мы познакомились и научились работать с основными алгоритмами сортировки